# Generated by Django 6.0.4 on 2026-04-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='Symbol giełdowy, np. AAPL', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Pełna nazwa spółki lub funduszu', max_length=100)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Akcja'), ('ETF', 'Fundusz ETF')], default='STOCK', max_length=5)),
                ('current_price_pln', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Czas ostatniej aktualizacji z API')),
            ],
        ),
    ]
