# Generated by Django 6.0.4 on 2026-04-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialasset',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialasset',
            name='current_price_pln',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialasset',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
